# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGzEg4KU1uEdgUUhzXozM8BQEGNYlc1g
"""

!pip install -q tf-keras pillow

import numpy as np
from PIL import Image, ImageOps
from tf_keras.models import load_model

# Load the trained model and labels
model = load_model("/content/keras_model.h5", compile=False)

with open("/content/labels.txt", "r", encoding="utf-8") as file:
    class_names = file.readlines()

# Load the test image
image = Image.open("/content/servo_motor_front.png").convert("RGB")

# Prepare the image for the model
image = ImageOps.fit(image, (224, 224), Image.Resampling.LANCZOS)
image_array = np.asarray(image)
normalized_image = (image_array.astype(np.float32) / 127.5) - 1

data = np.empty((1, 224, 224, 3), dtype=np.float32)
data[0] = normalized_image

# Predict
prediction = model.predict(data)
index = np.argmax(prediction)
class_name = class_names[index].strip()
confidence = prediction[0][index] * 100

print("Predicted class:", class_name)
print(f"Confidence: {confidence:.2f}%")